let dataCH = [
  {
    "DESCRIPCIÓN DE LA INTERVENCIÓN": "PROYECTO DE VIVIENDA CUALITATIVA EN EL MUNICIPIO DE AZURDUY -FASE(XV) 2025- CHUQUISACA",
    "MONTOS": " 3.999.978 ",
    "MES": "6/5/2026",
    "DEPTO": "CHUQUISACA",
    "MUNICIPIO": "AZURDUY"
  },
  {
    "DESCRIPCIÓN DE LA INTERVENCIÓN": "PROYECTO DE VIVIENDA CUALITATIVA EN EL MUNICIPIO DE MUYUPAMPA -FASE(XIII) 2025- CHUQUISACA",
    "MONTOS": " 3.032.260 ",
    "MES": "8/5/2026",
    "DEPTO": "CHUQUISACA",
    "MUNICIPIO": "MUYUPAMPA"
  },
  {
    "DESCRIPCIÓN DE LA INTERVENCIÓN": "PROYECTO DE VIVIENDA CUALITATIVA EN EL MUNICIPIO DE SOPACHUY -FASE(XV) 2025- CHUQUISACA",
    "MONTOS": " 3.519.753 ",
    "MES": "8/5/2026",
    "DEPTO": "CHUQUISACA",
    "MUNICIPIO": "SOPACHUY"
  },
  {
    "DESCRIPCIÓN DE LA INTERVENCIÓN": "PROYECTO DE VIVIENDA CUALITATIVA EN EL MUNICIPIO DE CAMARGO -FASE(XVI) 2025- CHUQUISACA",
    "MONTOS": " 3.030.564 ",
    "MES": "12/5/2026",
    "DEPTO": "CHUQUISACA",
    "MUNICIPIO": "CAMARGO"
  },
  {
    "DESCRIPCIÓN DE LA INTERVENCIÓN": "Proyecto del PER III\nPiedra Fundamental del Proyecto: CONST. ELECTRIFICACION RURAL DISTRITO SUPAS MUNICIPIO DE VILLA CHARCAS (CHUQUISACA)",
    "MONTOS": " 6.920.000 ",
    "MES": "15/5/2026",
    "DEPTO": "CHUQUISACA",
    "MUNICIPIO": "SIN IDENTIFICAR"
  },
  {
    "DESCRIPCIÓN DE LA INTERVENCIÓN": "AMPL. DE SISTEMA DE RIEGO PRESURIZADO EL PERAL",
    "MONTOS": " 3.438.646 ",
    "MES": "20/5/2026",
    "DEPTO": "CHUQUISACA",
    "MUNICIPIO": "MUNICIPIO DE PRESTO"
  },
  {
    "DESCRIPCIÓN DE LA INTERVENCIÓN": "CONST. PUENTE VEHICULAR RIO SAN JUAN DE HORCAS - MUNICIPIO DE SOPACHUY",
    "MONTOS": " 2.201.883 ",
    "MES": "21/5/2026",
    "DEPTO": "CHUQUISACA",
    "MUNICIPIO": "MUNICIPIO DE SOPACHUY"
  },
  {
    "DESCRIPCIÓN DE LA INTERVENCIÓN": "CONST. PUENTE VEHICULAR SUCUMAYU. COMUNIDAD PALAJLA",
    "MONTOS": " 1.080.344 ",
    "MES": "21/5/2026",
    "DEPTO": "CHUQUISACA",
    "MUNICIPIO": "COMUNIDAD PALAJLA"
  },
  {
    "DESCRIPCIÓN DE LA INTERVENCIÓN": "CONSTRUCCION PUENTE VEHICULAR POTREROS (MONTEAGUDO)",
    "MONTOS": " 1.999.963 ",
    "MES": "22/5/2026",
    "DEPTO": "CHUQUISACA",
    "MUNICIPIO": "SIN IDENTIFICAR"
  },
  {
    "DESCRIPCIÓN DE LA INTERVENCIÓN": "CONST. UNIDAD EDUCATIVA ANTONIO TOVAR - TARVITA",
    "MONTOS": " 6.009.101 ",
    "MES": "31/5/2026",
    "DEPTO": "CHUQUISACA",
    "MUNICIPIO": "GOBIERNO AUTONOMO MUNICIPAL DE TARVITA "
  },
  {
    "DESCRIPCIÓN DE LA INTERVENCIÓN": "CONST. UNIDAD EDUCATIVA 21 DE SEPTIEMBRE - VILLA CHARCAS",
    "MONTOS": " 5.898.259 ",
    "MES": "31/5/2026",
    "DEPTO": "CHUQUISACA",
    "MUNICIPIO": "GOBIERNO AUTONOMO MUNICIPAL DE VILLA CHÁRCAS"
  }
]